## Libraries

In [15]:
import cv2
import os
import numpy as np

##  Reading a Video file and getting Frames (Images) and writing them to System

In [16]:
input_file_name='ftna3'
cap=cv2.VideoCapture(input_file_name+".mp4")
count=0

In [17]:
shape=(0,0,0)
shape_set=False
while(cap.isOpened()):
    ret,frame=cap.read()
    if(not shape_set):
        shape=frame.shape
        shape_set=True
    if(ret==True):
        cv2.imwrite(input_file_name+"frame_"+str(count)+".jpg",frame)
        count=count+1
    else:
        break
cap.release()
cv2.destroyAllWindows()
print(shape)

(480, 640, 3)


## Reading Thermal Images stored on the System and Storing them in a numpy Array

In [18]:
# np_img=[]

# for i in range(0,640):
#     np_img.append([])
#     for j in range(0,480):
#         np_img[i].append([])

# np.zeros((640,480,count))

# for i in range(0,count):
#     img=cv2.imread("frame_"+str(i)+".jpg")
#     for j in range(0,640):
#         for k in range(0,480):
#             np_img[j][k].append(img[j][k])

# np_img=np.array(np_img, dtype=complex)

In [19]:
np_img=np.zeros((shape[0],shape[1],count),dtype=complex)

for i in range(0,count):
    img=cv2.imread(input_file_name+"frame_"+str(i)+".jpg")
    img=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    for j in range(0,shape[0]):
        for k in range(0,shape[1]):
            np_img[j][k][i]=img[j][k]

## Printing Dimension of numpy Array

In [20]:
print(np_img.shape)

(480, 640, 201)


## Calculation of Phase to multipled to Fourier Coefficients of times series value of same pixel in Thermogram (Thermal Image)

In [21]:
z=0.002
k=0.33
c=3780
p=1057
X=k/(c*p)
f=0.01

phase=np.exp(z*np.sqrt(np.pi*f/X)*(1+1j))

## Printing Phase

In [22]:
print(phase)

(1.1362276288627418+3.2396754954446267j)


## Calculation of Blood Flow from pixel values of series of Thermograms

In [23]:
for i in range(0,shape[0]):
    for j in range(0,shape[1]):
        np_img[i][j]=np.fft.fft(np_img[i][j])*phase

for i in range(0,shape[0]):
    for j in range(0,shape[1]):
        np_img[i][j]=np.fft.ifft(np_img[i][j])

## Printing Blood Flow Values

In [24]:
print(np_img.shape)

(480, 640, 201)


## Seperation Blood Flow values and Creating Images and Writing to System

In [25]:
# img=[]
# frame_array=[]

# for i in range(0,count):
#     for j in range(0,640):
#         img.append([])
#         for k in range(0,480):
#             img[j].append(np_img[j][k][i])
#             print(np_img[j][k][i])
#     img=np.uint8(img)
#     print(img)
#     cv2.imwrite("b_frame_"+str(i)+".jpg",img)
#     frame_array.append(img)
#     img=[]

In [26]:
frame_array=[]

for i in range(0,count):
    img=np.zeros((shape[0],shape[1]),dtype=complex)
    print(img.shape)
    for j in range(0,shape[0]):
        for k in range(0,shape[1]):
            img[j][k]=np_img[j][k][i]
    img=np.uint8(img)
    img=cv2.applyColorMap(img,cv2.COLORMAP_HSV)
#     img=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    print(img)
#     img=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    cv2.imwrite(input_file_name+"_b_frame_"+str(i)+".jpg",img)
    frame_array.append(img)

(480, 640)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: ComplexWarning: Casting complex values to real discards the imaginary part
  if __name__ == '__main__':


[[[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 156 255]
  [  0 156 255]]

 [[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 156 255]
  [  0 156 255]]

 [[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 156 255]
  [  0 156 255]]

 ...

 [[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 162 255]
  [  0 162 255]]

 [[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 162 255]
  [  0 162 255]]

 [[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 162 255]
  [  0 162 255]]]
(480, 640)
[[[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 156 255]
  [  0 156 255]]

 [[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 156 255]
  [  0 156 255]]

 [[  0 162 255]
  [  0 162 255]
  [  0 162 255]
  ...
  [  0 162 255]
  [  0 156 255]
  [  0 156 255]]

 ...

 [[  0 162 255]
  [  0 162 255]
  [  0 16

[[[174 255   0]
  [174 255   0]
  [180 255   0]
  ...
  [  0 255  66]
  [  0 255   0]
  [  0 255   0]]

 [[180 255   0]
  [180 255   0]
  [180 255   0]
  ...
  [  0 255  90]
  [  0 255  36]
  [  0 255   6]]

 [[180 255   0]
  [180 255   0]
  [180 255   0]
  ...
  [  0 255  78]
  [  0 255  36]
  [  0 255  18]]

 ...

 [[ 18 255   0]
  [ 18 255   0]
  [ 12 255   0]
  ...
  [  0 255 120]
  [  0 255 168]
  [  0 255 198]]

 [[ 18 255   0]
  [ 12 255   0]
  [ 12 255   0]
  ...
  [  0 255 150]
  [  0 255 180]
  [  0 255 156]]

 [[ 18 255   0]
  [ 12 255   0]
  [ 12 255   0]
  ...
  [  0 255 192]
  [  0 255 186]
  [  0 255 102]]]
(480, 640)
[[[150 255   0]
  [168 255   0]
  [168 255   0]
  ...
  [  0 255  84]
  [  0 255  54]
  [  0 255  36]]

 [[144 255   0]
  [156 255   0]
  [162 255   0]
  ...
  [  0 255  72]
  [  0 255  72]
  [  0 255  36]]

 [[126 255   0]
  [144 255   0]
  [150 255   0]
  ...
  [  0 255  72]
  [  0 255  72]
  [  0 255  18]]

 ...

 [[  0 255   6]
  [  0 255  18]
  [  0 25

[[[120 255   0]
  [114 255   0]
  [108 255   0]
  ...
  [  0 255  84]
  [  0 255  96]
  [  0 255  84]]

 [[120 255   0]
  [114 255   0]
  [108 255   0]
  ...
  [  0 255  48]
  [  0 255  48]
  [  0 255  42]]

 [[120 255   0]
  [114 255   0]
  [108 255   0]
  ...
  [  0 255  78]
  [  0 255  72]
  [  0 255  66]]

 ...

 [[  0 255  72]
  [  0 255  72]
  [  0 255  72]
  ...
  [  0 250 247]
  [  0 255 228]
  [  0 250 247]]

 [[  0 255  54]
  [  0 255  66]
  [  0 255  66]
  ...
  [  0 255 216]
  [  0 255 192]
  [  0 255 234]]

 [[  0 255  48]
  [  0 255  54]
  [  0 255  66]
  ...
  [  0 255 240]
  [  0 255 204]
  [  0 253 244]]]
(480, 640)
[[[114 255   0]
  [114 255   0]
  [120 255   0]
  ...
  [  0 255  90]
  [  0 255  54]
  [  0 255  72]]

 [[114 255   0]
  [114 255   0]
  [120 255   0]
  ...
  [  0 255 102]
  [  0 255  72]
  [  0 255  90]]

 [[114 255   0]
  [114 255   0]
  [120 255   0]
  ...
  [  0 255 102]
  [  0 255  66]
  [  0 255  66]]

 ...

 [[  0 255  54]
  [  0 255  54]
  [  0 25

[[[ 96 255   0]
  [ 96 255   0]
  [ 96 255   0]
  ...
  [  0 255  90]
  [  0 255  90]
  [  0 255  90]]

 [[ 84 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255 102]
  [  0 255  96]
  [  0 255  84]]

 [[ 78 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255 102]
  [  0 255 120]
  [  0 255 144]]

 ...

 [[  0 255  72]
  [  0 255  72]
  [  0 255  66]
  ...
  [  0 255 228]
  [  0 255 222]
  [  0 253 244]]

 [[  0 255  78]
  [  0 255  78]
  [  0 255  72]
  ...
  [  0 247 250]
  [  0 234 255]
  [  0 210 255]]

 [[  0 255  78]
  [  0 255  72]
  [  0 255  72]
  ...
  [  0 250 247]
  [  0 255 234]
  [  0 255 228]]]
(480, 640)
[[[ 84 255   0]
  [ 96 255   0]
  [ 96 255   0]
  ...
  [  0 255 126]
  [  0 255 102]
  [  0 255  90]]

 [[ 96 255   0]
  [102 255   0]
  [ 96 255   0]
  ...
  [  0 255 108]
  [  0 255 108]
  [  0 255 108]]

 [[ 78 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255  90]
  [  0 255  96]
  [  0 255 120]]

 ...

 [[  0 255  66]
  [  0 255  66]
  [  0 25

[[[ 72 255   0]
  [ 72 255   0]
  [ 72 255   0]
  ...
  [  0 255 120]
  [  0 255 132]
  [  0 255 126]]

 [[ 72 255   0]
  [ 72 255   0]
  [ 72 255   0]
  ...
  [  0 255 108]
  [  0 255 102]
  [  0 255  96]]

 [[ 78 255   0]
  [ 78 255   0]
  [ 72 255   0]
  ...
  [  0 255  96]
  [  0 255  96]
  [  0 255 102]]

 ...

 [[  0 255  84]
  [  0 255  84]
  [  0 255  90]
  ...
  [  0 216 255]
  [  0 216 255]
  [  0 228 255]]

 [[  0 255  84]
  [  0 255  84]
  [  0 255  90]
  ...
  [  0 247 250]
  [  0 247 250]
  [  0 255 234]]

 [[  0 255  84]
  [  0 255  84]
  [  0 255  90]
  ...
  [  0 210 255]
  [  0 240 255]
  [  0 255 222]]]
(480, 640)
[[[ 96 255   0]
  [ 96 255   0]
  [ 96 255   0]
  ...
  [  0 255  84]
  [  0 255 108]
  [  0 255 126]]

 [[ 84 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255  90]
  [  0 255  96]
  [  0 255  96]]

 [[ 78 255   0]
  [ 78 255   0]
  [ 84 255   0]
  ...
  [  0 255  72]
  [  0 255  84]
  [  0 255  84]]

 ...

 [[  0 255  54]
  [  0 255  66]
  [  0 25

[[[ 60 255   0]
  [ 72 255   0]
  [ 78 255   0]
  ...
  [  0 255 120]
  [  0 255 132]
  [  0 255  96]]

 [[ 66 255   0]
  [ 72 255   0]
  [ 72 255   0]
  ...
  [  0 255 126]
  [  0 255 138]
  [  0 255 102]]

 [[ 72 255   0]
  [ 72 255   0]
  [ 72 255   0]
  ...
  [  0 255 102]
  [  0 255 126]
  [  0 255 120]]

 ...

 [[  0 255  72]
  [  0 255  66]
  [  0 255  66]
  ...
  [  0 250 247]
  [  0 228 255]
  [  0 204 255]]

 [[  0 255  66]
  [  0 255  66]
  [  0 255  66]
  ...
  [  0 250 247]
  [  0 247 250]
  [  0 240 255]]

 [[  0 255  66]
  [  0 255  66]
  [  0 255  66]
  ...
  [  0 253 244]
  [  0 253 244]
  [  0 250 247]]]
(480, 640)
[[[ 78 255   0]
  [ 66 255   0]
  [ 66 255   0]
  ...
  [  0 255 126]
  [  0 255 138]
  [  0 255 126]]

 [[ 78 255   0]
  [ 66 255   0]
  [ 66 255   0]
  ...
  [  0 255 132]
  [  0 255 144]
  [  0 255 138]]

 [[ 72 255   0]
  [ 66 255   0]
  [ 66 255   0]
  ...
  [  0 255 138]
  [  0 255 150]
  [  0 255 168]]

 ...

 [[  0 255  78]
  [  0 255  78]
  [  0 25

[[[ 48 255   0]
  [ 54 255   0]
  [ 60 255   0]
  ...
  [  0 255 150]
  [  0 255 138]
  [  0 255  96]]

 [[ 54 255   0]
  [ 54 255   0]
  [ 54 255   0]
  ...
  [  0 255 144]
  [  0 255 144]
  [  0 255 132]]

 [[ 60 255   0]
  [ 54 255   0]
  [ 48 255   0]
  ...
  [  0 255 138]
  [  0 255 144]
  [  0 255 144]]

 ...

 [[  0 255  72]
  [  0 255  72]
  [  0 255  72]
  ...
  [  0 192 255]
  [  0 174 255]
  [  0 180 255]]

 [[  0 255  66]
  [  0 255  66]
  [  0 255  66]
  ...
  [  0 186 255]
  [  0 216 255]
  [  0 253 244]]

 [[  0 255  66]
  [  0 255  66]
  [  0 255  66]
  ...
  [  0 222 255]
  [  0 234 255]
  [  0 247 250]]]
(480, 640)
[[[ 54 255   0]
  [ 54 255   0]
  [ 48 255   0]
  ...
  [  0 255 138]
  [  0 255  96]
  [  0 255 120]]

 [[ 48 255   0]
  [ 42 255   0]
  [ 42 255   0]
  ...
  [  0 255 144]
  [  0 255  84]
  [  0 255  90]]

 [[ 42 255   0]
  [ 42 255   0]
  [ 48 255   0]
  ...
  [  0 255 144]
  [  0 255 102]
  [  0 255 132]]

 ...

 [[  0 255  54]
  [  0 255  54]
  [  0 25

[[[ 48 255   0]
  [ 48 255   0]
  [ 48 255   0]
  ...
  [  0 255 126]
  [  0 255 108]
  [  0 255  96]]

 [[ 48 255   0]
  [ 48 255   0]
  [ 48 255   0]
  ...
  [  0 255 126]
  [  0 255 126]
  [  0 255 132]]

 [[ 48 255   0]
  [ 48 255   0]
  [ 48 255   0]
  ...
  [  0 255 120]
  [  0 255 108]
  [  0 255 126]]

 ...

 [[  0 255  96]
  [  0 255  96]
  [  0 255  96]
  ...
  [  0 192 255]
  [  0 192 255]
  [  0 210 255]]

 [[  0 255  96]
  [  0 255  90]
  [  0 255  90]
  ...
  [  0 240 255]
  [  0 234 255]
  [  0 234 255]]

 [[  0 255  84]
  [  0 255  78]
  [  0 255  78]
  ...
  [  0 255 228]
  [  0 250 247]
  [  0 222 255]]]
(480, 640)
[[[  0 204 255]
  [  0 204 255]
  [  0 204 255]
  ...
  [  0 228 255]
  [  0 234 255]
  [  0 192 255]]

 [[  0 210 255]
  [  0 210 255]
  [  0 210 255]
  ...
  [  0 216 255]
  [  0 228 255]
  [  0 186 255]]

 [[  0 216 255]
  [  0 216 255]
  [  0 216 255]
  ...
  [  0 204 255]
  [  0 216 255]
  [  0 186 255]]

 ...

 [[  0 210 255]
  [  0 210 255]
  [  0 21

[[[ 84 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255  90]
  [  0 255  78]
  [  0 255  90]]

 [[ 84 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255  78]
  [  0 255  72]
  [  0 255  90]]

 [[ 84 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255  72]
  [  0 255  54]
  [  0 255  84]]

 ...

 [[  0 255  36]
  [  0 255  36]
  [  0 255  36]
  ...
  [  0 255 234]
  [  0 250 247]
  [  0 234 255]]

 [[  0 255  36]
  [  0 255  36]
  [  0 255  36]
  ...
  [  0 253 244]
  [  0 255 234]
  [  0 255 240]]

 [[  0 255  36]
  [  0 255  36]
  [  0 255  36]
  ...
  [  0 255 240]
  [  0 255 222]
  [  0 255 228]]]
(480, 640)
[[[ 78 255   0]
  [ 78 255   0]
  [ 78 255   0]
  ...
  [  0 255  78]
  [  0 255  78]
  [  0 255  54]]

 [[ 84 255   0]
  [ 84 255   0]
  [ 78 255   0]
  ...
  [  0 255  42]
  [  0 255  42]
  [  0 255  24]]

 [[ 84 255   0]
  [ 84 255   0]
  [ 78 255   0]
  ...
  [  0 255  72]
  [  0 255  72]
  [  0 255  78]]

 ...

 [[  0 255  36]
  [  0 255  30]
  [  0 25

[[[ 48 255   0]
  [ 48 255   0]
  [ 48 255   0]
  ...
  [  0 255 132]
  [  0 255 138]
  [  0 255 144]]

 [[ 48 255   0]
  [ 48 255   0]
  [ 48 255   0]
  ...
  [  0 255 126]
  [  0 255 132]
  [  0 255 138]]

 [[ 42 255   0]
  [ 42 255   0]
  [ 42 255   0]
  ...
  [  0 255 120]
  [  0 255 108]
  [  0 255 102]]

 ...

 [[  0 255  84]
  [  0 255  84]
  [  0 255  90]
  ...
  [  0 222 255]
  [  0 210 255]
  [  0 138 255]]

 [[  0 255  90]
  [  0 255  90]
  [  0 255  90]
  ...
  [  0 216 255]
  [  0 228 255]
  [  0 174 255]]

 [[  0 255  96]
  [  0 255  96]
  [  0 255  96]
  ...
  [  0 210 255]
  [  0 240 255]
  [  0 234 255]]]
(480, 640)
[[[ 72 255   0]
  [ 72 255   0]
  [ 72 255   0]
  ...
  [  0 255 144]
  [  0 255 132]
  [  0 255 132]]

 [[ 72 255   0]
  [ 72 255   0]
  [ 72 255   0]
  ...
  [  0 255 138]
  [  0 255 126]
  [  0 255 126]]

 [[ 66 255   0]
  [ 66 255   0]
  [ 66 255   0]
  ...
  [  0 255 138]
  [  0 255 126]
  [  0 255 132]]

 ...

 [[  0 255  54]
  [  0 255  54]
  [  0 25

[[[ 84 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255  96]
  [  0 255 108]
  [  0 255 120]]

 [[ 84 255   0]
  [ 84 255   0]
  [ 84 255   0]
  ...
  [  0 255 108]
  [  0 255 126]
  [  0 255 132]]

 [[ 78 255   0]
  [ 78 255   0]
  [ 78 255   0]
  ...
  [  0 255 102]
  [  0 255 108]
  [  0 255 108]]

 ...

 [[  0 255  36]
  [  0 255  30]
  [  0 255  30]
  ...
  [  0 255 228]
  [  0 255 234]
  [  0 250 247]]

 [[  0 255  42]
  [  0 255  30]
  [  0 255  30]
  ...
  [  0 253 244]
  [  0 253 244]
  [  0 247 250]]

 [[  0 255  42]
  [  0 255  30]
  [  0 255  30]
  ...
  [  0 250 247]
  [  0 240 255]
  [  0 222 255]]]
(480, 640)
[[[ 54 255   0]
  [ 48 255   0]
  [ 48 255   0]
  ...
  [  0 255 150]
  [  0 255 168]
  [  0 255 156]]

 [[ 48 255   0]
  [ 42 255   0]
  [ 42 255   0]
  ...
  [  0 255 144]
  [  0 255 168]
  [  0 255 180]]

 [[ 30 255   0]
  [ 42 255   0]
  [ 42 255   0]
  ...
  [  0 255 156]
  [  0 255 168]
  [  0 255 174]]

 ...

 [[  0 255  78]
  [  0 255  72]
  [  0 25

[[[ 24 255   0]
  [ 24 255   0]
  [ 18 255   0]
  ...
  [  0 255 192]
  [  0 255 198]
  [  0 255 198]]

 [[ 24 255   0]
  [ 18 255   0]
  [ 18 255   0]
  ...
  [  0 255 216]
  [  0 255 204]
  [  0 255 186]]

 [[ 24 255   0]
  [ 18 255   0]
  [ 18 255   0]
  ...
  [  0 255 192]
  [  0 255 168]
  [  0 255 138]]

 ...

 [[  0 255 108]
  [  0 255 108]
  [  0 255 108]
  ...
  [  0 186 255]
  [  0 192 255]
  [  0 210 255]]

 [[  0 255 108]
  [  0 255 108]
  [  0 255 108]
  ...
  [  0 192 255]
  [  0 204 255]
  [  0 204 255]]

 [[  0 255 102]
  [  0 255 108]
  [  0 255 108]
  ...
  [  0 216 255]
  [  0 210 255]
  [  0 204 255]]]
(480, 640)
[[[ 42 255   0]
  [ 30 255   0]
  [ 30 255   0]
  ...
  [  0 255 126]
  [  0 255 132]
  [  0 255 108]]

 [[ 30 255   0]
  [ 30 255   0]
  [ 30 255   0]
  ...
  [  0 255 132]
  [  0 255 144]
  [  0 255 126]]

 [[ 30 255   0]
  [ 30 255   0]
  [ 30 255   0]
  ...
  [  0 255 108]
  [  0 255 126]
  [  0 255 126]]

 ...

 [[  0 255  84]
  [  0 255  90]
  [  0 25

[[[ 78 255   0]
  [ 78 255   0]
  [ 78 255   0]
  ...
  [  0 255  96]
  [  0 255  96]
  [  0 255  90]]

 [[ 78 255   0]
  [ 78 255   0]
  [ 78 255   0]
  ...
  [  0 255 120]
  [  0 255 108]
  [  0 255 102]]

 [[ 78 255   0]
  [ 78 255   0]
  [ 78 255   0]
  ...
  [  0 255 120]
  [  0 255 108]
  [  0 255 102]]

 ...

 [[  0 255   6]
  [  0 255   0]
  [  0 255   6]
  ...
  [  0 255 174]
  [  0 255 168]
  [  0 255 198]]

 [[  0 255   6]
  [  0 255   0]
  [  0 255  18]
  ...
  [  0 255 192]
  [  0 255 204]
  [  0 250 247]]

 [[  0 255   6]
  [  0 255   0]
  [  0 255  18]
  ...
  [  0 250 247]
  [  0 240 255]
  [  0 222 255]]]
(480, 640)
[[[ 78 255   0]
  [ 78 255   0]
  [ 72 255   0]
  ...
  [  0 255 102]
  [  0 255  90]
  [  0 255  72]]

 [[ 78 255   0]
  [ 78 255   0]
  [ 78 255   0]
  ...
  [  0 255  96]
  [  0 255  90]
  [  0 255  84]]

 [[ 78 255   0]
  [ 72 255   0]
  [ 72 255   0]
  ...
  [  0 255  78]
  [  0 255  78]
  [  0 255  78]]

 ...

 [[  0 255  30]
  [  0 255  30]
  [  0 25

[[[234 255   0]
  [228 255   0]
  [228 255   0]
  ...
  [132 255   0]
  [150 255   0]
  [150 255   0]]

 [[244 253   0]
  [234 255   0]
  [244 253   0]
  ...
  [144 255   0]
  [156 255   0]
  [168 255   0]]

 [[244 253   0]
  [244 253   0]
  [244 253   0]
  ...
  [180 255   0]
  [174 255   0]
  [168 255   0]]

 ...

 [[144 255   0]
  [132 255   0]
  [144 255   0]
  ...
  [ 78 255   0]
  [ 72 255   0]
  [ 12 255   0]]

 [[144 255   0]
  [132 255   0]
  [144 255   0]
  ...
  [ 60 255   0]
  [ 60 255   0]
  [ 12 255   0]]

 [[144 255   0]
  [132 255   0]
  [144 255   0]
  ...
  [  0 255  36]
  [  0 255  24]
  [  0 255  18]]]
(480, 640)
[[[222 255   0]
  [222 255   0]
  [222 255   0]
  ...
  [150 255   0]
  [132 255   0]
  [132 255   0]]

 [[210 255   0]
  [216 255   0]
  [216 255   0]
  ...
  [132 255   0]
  [150 255   0]
  [156 255   0]]

 [[204 255   0]
  [210 255   0]
  [210 255   0]
  ...
  [150 255   0]
  [162 255   0]
  [162 255   0]]

 ...

 [[120 255   0]
  [126 255   0]
  [132 25

[[[150 255   0]
  [150 255   0]
  [150 255   0]
  ...
  [ 84 255   0]
  [ 84 255   0]
  [102 255   0]]

 [[150 255   0]
  [150 255   0]
  [150 255   0]
  ...
  [ 84 255   0]
  [ 78 255   0]
  [ 72 255   0]]

 [[150 255   0]
  [150 255   0]
  [150 255   0]
  ...
  [ 84 255   0]
  [102 255   0]
  [ 84 255   0]]

 ...

 [[ 42 255   0]
  [ 42 255   0]
  [ 42 255   0]
  ...
  [  0 255  90]
  [  0 255  78]
  [  0 255  48]]

 [[ 42 255   0]
  [ 42 255   0]
  [ 42 255   0]
  ...
  [  0 255  90]
  [  0 255  66]
  [  0 255  42]]

 [[ 42 255   0]
  [ 42 255   0]
  [ 42 255   0]
  ...
  [  0 255 102]
  [  0 255  84]
  [  0 255  78]]]
(480, 640)
[[[150 255   0]
  [144 255   0]
  [144 255   0]
  ...
  [ 72 255   0]
  [ 84 255   0]
  [ 78 255   0]]

 [[144 255   0]
  [144 255   0]
  [144 255   0]
  ...
  [ 66 255   0]
  [ 72 255   0]
  [ 72 255   0]]

 [[144 255   0]
  [144 255   0]
  [144 255   0]
  ...
  [ 78 255   0]
  [ 96 255   0]
  [ 96 255   0]]

 ...

 [[ 48 255   0]
  [ 48 255   0]
  [ 48 25

[[[  0 144 255]
  [  0 144 255]
  [  0 144 255]
  ...
  [  0 156 255]
  [  0 168 255]
  [  0 168 255]]

 [[  0 144 255]
  [  0 144 255]
  [  0 144 255]
  ...
  [  0 144 255]
  [  0 156 255]
  [  0 156 255]]

 [[  0 144 255]
  [  0 144 255]
  [  0 144 255]
  ...
  [  0 144 255]
  [  0 144 255]
  [  0 138 255]]

 ...

 [[  0 156 255]
  [  0 156 255]
  [  0 156 255]
  ...
  [  0 162 255]
  [  0 162 255]
  [  0 162 255]]

 [[  0 156 255]
  [  0 156 255]
  [  0 156 255]
  ...
  [  0 162 255]
  [  0 162 255]
  [  0 162 255]]

 [[  0 156 255]
  [  0 156 255]
  [  0 156 255]
  ...
  [  0 162 255]
  [  0 162 255]
  [  0 162 255]]]
(480, 640)
[[[150 255   0]
  [150 255   0]
  [150 255   0]
  ...
  [  0 255   0]
  [ 18 255   0]
  [  6 255   0]]

 [[150 255   0]
  [150 255   0]
  [150 255   0]
  ...
  [  0 255   6]
  [ 12 255   0]
  [ 18 255   0]]

 [[156 255   0]
  [150 255   0]
  [150 255   0]
  ...
  [  0 255  18]
  [  0 255   0]
  [ 12 255   0]]

 ...

 [[ 30 255   0]
  [ 30 255   0]
  [ 30 25

## Generating Blood Flow Video from Blood Flow Images

In [27]:
fps=2
out=cv2.VideoWriter("b_"+input_file_name+".avi",cv2.VideoWriter_fourcc(*'XVID'),fps,(shape[1],shape[0]))

for i in range(len(frame_array)):
    out.write(frame_array[i])

out.release()

## Printing length of Frame Array

In [28]:
print(len(frame_array))

201
