## Libraries

In [1]:
import cv2
import os
import numpy as np

##  Reading a Video file and getting Frames (Images) and writing them to System

In [2]:
input_file_name='ftna2'
cap=cv2.VideoCapture(input_file_name+".mp4")
count=0

In [3]:
shape=(0,0,0)
shape_set=False
while(cap.isOpened()):
    ret,frame=cap.read()
    if(not shape_set):
        shape=frame.shape
        shape_set=True
    if(ret==True):
        cv2.imwrite(input_file_name+"frame_"+str(count)+".jpg",frame)
        count=count+1
    else:
        break

cap.release()
cv2.destroyAllWindows()
print(shape)

(1080, 1440, 3)


## Reading Thermal Images stored on the System and Storing them in a numpy Array

In [4]:
# np_img=[]

# for i in range(0,640):
#     np_img.append([])
#     for j in range(0,480):
#         np_img[i].append([])

# np.zeros((640,480,count))

# for i in range(0,count):
#     img=cv2.imread("frame_"+str(i)+".jpg")
#     for j in range(0,640):
#         for k in range(0,480):
#             np_img[j][k].append(img[j][k])

# np_img=np.array(np_img, dtype=complex)

In [5]:
np_img=np.zeros((shape[0],shape[1],count,shape[2]),dtype=complex)

for i in range(0,count):
    img=cv2.imread(input_file_name+"frame_"+str(i)+".jpg")
    for j in range(0,shape[0]):
        for k in range(0,shape[1]):
            np_img[j][k][i]=img[j][k]

## Printing Dimension of numpy Array

In [6]:
print(np_img.shape)

(1080, 1440, 108, 3)


## Calculation of Phase to multipled to Fourier Coefficients of times series value of same pixel in Thermogram (Thermal Image)

In [7]:
z=0.002
k=0.33
c=3780
p=1057
X=k/(c*p)
f=0.01

phase=np.exp(z*np.sqrt(np.pi*f/X)*(1+1j))

## Printing Phase

In [8]:
print(phase)

(1.1362276288627418+3.2396754954446267j)


## Calculation of Blood Flow from pixel values of series of Thermograms

In [9]:
for i in range(0,shape[0]):
    for j in range(0,shape[1]):
        np_img[i][j]=np.fft.fft(np_img[i][j])*phase

for i in range(0,shape[0]):
    for j in range(0,shape[1]):
        np_img[i][j]=np.fft.ifft(np_img[i][j])

## Printing Blood Flow Values

In [10]:
print(np_img.shape)

(1080, 1440, 108, 3)


## Seperation Blood Flow values and Creating Images and Writing to System

In [11]:
# img=[]
# frame_array=[]

# for i in range(0,count):
#     for j in range(0,640):
#         img.append([])
#         for k in range(0,480):
#             img[j].append(np_img[j][k][i])
#             print(np_img[j][k][i])
#     img=np.uint8(img)
#     print(img)
#     cv2.imwrite("b_frame_"+str(i)+".jpg",img)
#     frame_array.append(img)
#     img=[]

In [12]:
frame_array=[]

for i in range(0,count):
    img=np.zeros((shape[0],shape[1],3),dtype=complex)
    for j in range(0,shape[0]):
        for k in range(0,shape[1]):
            img[j][k]=np_img[j][k][i]
    img=np.uint8(img)
    print(img)
    cv2.imwrite(input_file_name+"_b_frame_"+str(i)+".jpg",img)
    frame_array.append(img)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: ComplexWarning: Casting complex values to real discards the imaginary part
  


[[[162  35 195]
  [162  35 195]
  [162  35 195]
  ...
  [ 74  95 251]
  [ 74  95 251]
  [ 74  95 251]]

 [[162  35 195]
  [162  35 195]
  [162  35 195]
  ...
  [ 74  95 251]
  [ 74  95 251]
  [ 74  95 251]]

 [[162  35 195]
  [162  35 195]
  [162  35 195]
  ...
  [ 74  95 251]
  [ 74  95 251]
  [ 74  95 251]]

 ...

 [[ 86  92 249]
  [ 86  92 249]
  [ 86  92 249]
  ...
  [ 14 157  17]
  [ 14 157  17]
  [ 14 157  17]]

 [[ 86  89 247]
  [ 86  89 247]
  [ 86  89 247]
  ...
  [ 12 157  17]
  [ 12 157  17]
  [ 12 157  17]]

 [[ 87  90 248]
  [ 87  90 248]
  [ 87  90 248]
  ...
  [ 12 157  17]
  [ 12 157  17]
  [ 12 157  17]]]
[[[168  31 193]
  [168  31 193]
  [168  31 193]
  ...
  [ 86  89 247]
  [ 86  89 247]
  [ 86  89 247]]

 [[168  31 193]
  [168  31 193]
  [168  31 193]
  ...
  [ 86  89 247]
  [ 86  89 247]
  [ 86  89 247]]

 [[168  31 193]
  [168  31 193]
  [168  31 193]
  ...
  [ 86  89 247]
  [ 86  89 247]
  [ 86  89 247]]

 ...

 [[ 92  85 245]
  [ 92  85 245]
  [ 92  85 245]
  ..

[[[144  12  61]
  [144  12  61]
  [144  11  62]
  ...
  [170  27 181]
  [168  27 181]
  [168  27 181]]

 [[144  12  61]
  [144  12  61]
  [144  11  62]
  ...
  [170  27 181]
  [168  27 181]
  [168  27 181]]

 [[144  12  61]
  [144  12  61]
  [144  12  61]
  ...
  [170  27 181]
  [170  27 181]
  [170  27 181]]

 ...

 [[164  28 189]
  [165  29 190]
  [167  30 192]
  ...
  [ 52 118   5]
  [ 54 117   5]
  [ 54 117   5]]

 [[167  28 187]
  [164  29 187]
  [165  29 190]
  ...
  [ 51 118   5]
  [ 52 118   5]
  [ 52 118   5]]

 [[167  28 187]
  [167  28 187]
  [167  30 192]
  ...
  [ 51 118   5]
  [ 52 118   5]
  [ 52 118   5]]]
[[[126  14  39]
  [126  14  39]
  [126  14  39]
  ...
  [173  22 174]
  [173  22 174]
  [173  22 174]]

 [[126  14  39]
  [126  14  39]
  [126  14  39]
  ...
  [173  22 174]
  [173  22 174]
  [173  22 174]]

 [[126  14  39]
  [126  14  39]
  [126  14  39]
  ...
  [173  22 174]
  [173  22 174]
  [173  22 174]]

 ...

 [[163  28 186]
  [164  29 187]
  [164  29 187]
  ..

[[[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 [[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 [[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 ...

 [[178  17 165]
  [179  18 167]
  [177  18 167]
  ...
  [ 63 106   0]
  [ 65 105   0]
  [ 64 104 255]]

 [[178  17 163]
  [179  18 164]
  [177  19 164]
  ...
  [ 63 107 254]
  [ 63 107 254]
  [ 63 107 254]]

 [[178  17 163]
  [179  18 164]
  [178  20 165]
  ...
  [ 63 107 254]
  [ 63 107 254]
  [ 63 107 254]]]
[[[ 59  31   0]
  [ 59  31   0]
  [ 59  31   0]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 [[ 59  31   0]
  [ 59  31   0]
  [ 59  31   0]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 [[ 59  31   0]
  [ 59  31   0]
  [ 59  31   0]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 ...

 [[173  19 164]
  [173  19 164]
  [176  21 169]
  ..

[[[170   7  97]
  [170   7  97]
  [170   7  97]
  ...
  [172  26 179]
  [172  26 179]
  [172  26 179]]

 [[169   6  96]
  [169   6  96]
  [169   6  96]
  ...
  [172  26 179]
  [172  26 179]
  [172  26 179]]

 [[170   7  97]
  [170   7  97]
  [170   7  97]
  ...
  [172  26 179]
  [172  26 179]
  [172  26 179]]

 ...

 [[137  52 218]
  [135  52 218]
  [136  53 219]
  ...
  [ 39 130   9]
  [ 39 129  11]
  [ 39 129  11]]

 [[137  52 218]
  [135  52 218]
  [136  53 219]
  ...
  [ 37 130   9]
  [ 37 130   9]
  [ 37 130   9]]

 [[137  52 218]
  [135  52 218]
  [136  53 219]
  ...
  [ 37 130   9]
  [ 37 130   9]
  [ 37 130   9]]]
[[[167   9  93]
  [167   9  93]
  [167   9  93]
  ...
  [170  28 180]
  [170  28 180]
  [170  28 180]]

 [[165   7  92]
  [165   7  92]
  [165   7  92]
  ...
  [170  28 180]
  [170  28 180]
  [170  28 180]]

 [[167   9  93]
  [167   9  93]
  [167   9  93]
  ...
  [170  28 180]
  [170  28 180]
  [170  28 180]]

 ...

 [[145  48 214]
  [143  48 214]
  [143  48 214]
  ..

[[[ 95  19  15]
  [ 95  19  15]
  [ 95  20  14]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 [[ 95  19  15]
  [ 95  19  15]
  [ 95  20  14]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 [[ 95  19  15]
  [ 95  19  15]
  [ 95  20  14]
  ...
  [181  13 147]
  [181  13 147]
  [181  13 147]]

 ...

 [[165  31 193]
  [165  31 193]
  [165  31 193]
  ...
  [ 53 115   4]
  [ 53 115   4]
  [ 53 115   4]]

 [[163  32 193]
  [163  32 193]
  [163  32 193]
  ...
  [ 51 117   4]
  [ 51 117   4]
  [ 51 117   4]]

 [[163  32 193]
  [163  32 193]
  [163  32 193]
  ...
  [ 51 117   4]
  [ 51 117   4]
  [ 51 117   4]]]
[[[ 99  19  15]
  [ 99  19  15]
  [ 99  18  18]
  ...
  [179  17 155]
  [179  17 155]
  [179  17 155]]

 [[ 99  19  15]
  [ 99  19  15]
  [ 99  18  18]
  ...
  [179  17 155]
  [179  17 155]
  [179  17 155]]

 [[ 99  18  18]
  [ 99  18  18]
  [ 99  18  18]
  ...
  [179  17 155]
  [179  17 155]
  [179  17 155]]

 ...

 [[161  32 193]
  [161  32 193]
  [161  31 194]
  ..

[[[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [170   9  96]
  [170   9  96]
  [170   9  96]]

 [[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [170   9  96]
  [170   9  96]
  [170   9  96]]

 [[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [170   9  96]
  [170   9  96]
  [170   9  96]]

 ...

 [[179  10 142]
  [179  10 142]
  [180  11 143]
  ...
  [ 81  93 249]
  [ 84  92 249]
  [ 84  92 249]]

 [[180  10 139]
  [180  10 139]
  [179  10 142]
  ...
  [ 81  93 249]
  [ 84  92 249]
  [ 84  92 249]]

 [[180  10 139]
  [180  10 139]
  [179  10 142]
  ...
  [ 81  93 249]
  [ 84  92 249]
  [ 84  92 249]]]
[[[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [170  10  93]
  [170  10  93]
  [170  10  93]]

 [[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [170  10  93]
  [170  10  93]
  [170  10  93]]

 [[ 49  30   0]
  [ 49  30   0]
  [ 49  30   0]
  ...
  [169   7  93]
  [169   7  93]
  [169   7  93]]

 ...

 [[180  15 154]
  [180  15 154]
  [180  15 154]
  ..

[[[129  14  44]
  [129  14  44]
  [129  14  44]
  ...
  [177  21 171]
  [177  21 171]
  [177  21 171]]

 [[129  14  44]
  [129  14  44]
  [129  14  44]
  ...
  [177  21 171]
  [177  21 171]
  [177  21 171]]

 [[129  14  44]
  [129  14  44]
  [129  14  44]
  ...
  [177  21 171]
  [177  21 171]
  [177  21 171]]

 ...

 [[135  54 220]
  [135  54 220]
  [135  55 219]
  ...
  [ 38 126   8]
  [ 40 126   8]
  [ 38 126   8]]

 [[134  55 220]
  [134  55 220]
  [132  54 219]
  ...
  [ 37 128   7]
  [ 38 127   7]
  [ 37 128   7]]

 [[134  55 220]
  [134  55 220]
  [132  54 219]
  ...
  [ 37 128   7]
  [ 37 128   7]
  [ 37 128   7]]]
[[[126  14  42]
  [126  14  42]
  [126  14  42]
  ...
  [173  22 174]
  [173  22 174]
  [173  22 174]]

 [[126  14  42]
  [126  14  42]
  [126  14  42]
  ...
  [173  22 174]
  [173  22 174]
  [173  22 174]]

 [[126  14  42]
  [126  14  42]
  [126  14  42]
  ...
  [173  22 174]
  [173  22 174]
  [173  22 174]]

 ...

 [[136  53 219]
  [136  53 219]
  [135  52 218]
  ..

[[[ 68  27   0]
  [ 68  27   0]
  [ 68  27   0]
  ...
  [178  19 168]
  [178  19 168]
  [178  19 168]]

 [[ 68  27   0]
  [ 68  27   0]
  [ 68  27   0]
  ...
  [178  19 168]
  [178  19 168]
  [178  19 168]]

 [[ 65  27   0]
  [ 65  27   0]
  [ 65  27   0]
  ...
  [178  19 168]
  [178  19 168]
  [178  19 168]]

 ...

 [[159  35 201]
  [159  35 201]
  [159  36 198]
  ...
  [ 60 111   0]
  [ 60 111   0]
  [ 60 111   0]]

 [[159  35 201]
  [159  35 201]
  [159  36 198]
  ...
  [ 60 111   0]
  [ 60 111   0]
  [ 60 111   0]]

 [[159  35 201]
  [159  35 201]
  [159  36 198]
  ...
  [ 60 111   0]
  [ 60 111   0]
  [ 60 111   0]]]
[[[ 59  31   0]
  [ 59  31   0]
  [ 59  31   0]
  ...
  [178  19 168]
  [178  19 168]
  [178  19 168]]

 [[ 59  31   0]
  [ 59  31   0]
  [ 59  31   0]
  ...
  [178  19 168]
  [178  19 168]
  [178  19 168]]

 [[ 59  31   0]
  [ 59  31   0]
  [ 59  31   0]
  ...
  [178  19 168]
  [178  19 168]
  [178  19 168]]

 ...

 [[161  31 194]
  [161  31 194]
  [161  32 193]
  ..

## Generating Blood Flow Video from Blood Flow Images

In [13]:
fps=1
out=cv2.VideoWriter("b_"+input_file_name+".avi",cv2.VideoWriter_fourcc(*'XVID'),fps,(shape[1],shape[0]))

for i in range(len(frame_array)):
    out.write(frame_array[i])

out.release()

## Printing length of Frame Array

In [14]:
print(len(frame_array))

108
